export const featuredStudios = [
    {
        id: 1,
        slug: "pulse-studio",
        name: "Pulse Studio",
        location: "Westlands, Nairobi",
        county: "Nairobi",
        rating: 4.9,
        reviews: 241,
        bookings: 1824,
        verified: true,
        badge: "Editor's Choice",
        available: true,
        nextAvailable: "Today",
        responseTime: "15 min",
        price: 2500,
        priceLabel: "From KSh 2,500/hr",
        services: ["Recording", "Mixing", "Mastering"],
        genres: ["Afrobeats", "Hip Hop", "R&B"],
        equipment: ["Neumann U87", "Apollo x8", "Yamaha HS8"],
        rooms: 3,
        yearsActive: 8,
        image: "/images/studio.jpg",
    },
    {
        id: 2,
        slug: "dream-records",
        name: "Dream Records",
        location: "Nyali, Mombasa",
        county: "Mombasa",
        rating: 5.0,
        reviews: 189,
        bookings: 1260,
        verified: true,
        badge: "Top Rated",
        available: true,
        nextAvailable: "Today",
        responseTime: "10 min",
        price: 3000,
        priceLabel: "From KSh 3,000/hr",
        services: ["Recording", "Production"],
        genres: ["Afrobeats", "Dancehall"],
        equipment: ["AKG C414", "Focusrite Red", "KRK Rokit"],
        rooms: 2,
        yearsActive: 6,
        image: "/images/studio.jpg",
    },
    {
        id: 3,
        slug: "black-room",
        name: "Black Room",
        location: "Milimani, Kisumu",
        county: "Kisumu",
        rating: 4.8,
        reviews: 127,
        bookings: 894,
        verified: true,
        badge: "Podcast Ready",
        available: false,
        nextAvailable: "Tomorrow",
        responseTime: "30 min",
        price: 1800,
        priceLabel: "From KSh 1,800/hr",
        services: ["Podcast", "Voice Over"],
        genres: ["Podcast", "Voice"],
        equipment: ["Shure SM7B", "RØDECaster Pro"],
        rooms: 2,
        yearsActive: 5,
        image: "/images/studio.jpg",
    },
    {
        id: 4,
        slug: "bluewave-studio",
        name: "BlueWave Studio",
        location: "Nakuru CBD",
        county: "Nakuru",
        rating: 4.9,
        reviews: 305,
        bookings: 2050,
        verified: true,
        badge: "Most Booked",
        available: true,
        nextAvailable: "In 2 hours",
        responseTime: "12 min",
        price: 2700,
        priceLabel: "From KSh 2,700/hr",
        services: ["Recording", "Mastering"],
        genres: ["Hip Hop", "Trap", "Gospel"],
        equipment: ["Universal Audio", "Genelec Monitors"],
        rooms: 4,
        yearsActive: 9,
        image: "/images/studio.jpg",
    },
    {
        id: 5,
        slug: "echo-studios",
        name: "Echo Studios",
        location: "Eldoret Town",
        county: "Uasin Gishu",
        rating: 4.7,
        reviews: 94,
        bookings: 642,
        verified: false,
        badge: "New",
        available: true,
        nextAvailable: "Today",
        responseTime: "45 min",
        price: 2200,
        priceLabel: "From KSh 2,200/hr",
        services: ["Mixing", "Mastering"],
        genres: ["Pop", "Afropop"],
        equipment: ["SSL Interface", "Adam Audio A7X"],
        rooms: 2,
        yearsActive: 3,
        image: "/images/studio.jpg",
    },
    {
        id: 6,
        slug: "royal-sound",
        name: "Royal Sound",
        location: "Karen, Nairobi",
        county: "Nairobi",
        rating: 5.0,
        reviews: 412,
        bookings: 3218,
        verified: true,
        badge: "Premium",
        available: true,
        nextAvailable: "Now",
        responseTime: "5 min",
        price: 4000,
        priceLabel: "From KSh 4,000/hr",
        services: ["Recording", "Production"],
        genres: ["Afrobeats", "Pop", "Gospel"],
        equipment: ["Neve Console", "Neumann U87", "Barefoot Monitors"],
        rooms: 5,
        yearsActive: 12,
        image: "/images/studio.jpg",
    },
];